blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.blog_title, name='blog_title'),
    # 文章详情页，?P<article_id>\d匹配一个数字字符并将该字符赋值给参数article_id,传递给视图函数views.blog_content
    url(r'(?P<article_id>\d)/$', views.blog_content, name='blog_content'),
    url(r'^about/$', views.blog_about, name='blog_about'),
    url(r'^course/$', views.blog_course, name='blog_course'),
    url(r'^contact/$', views.blog_contact, name='blog_contact'),
]

comment/urls.py
from django.conf.urls import url
from . import views

urlpatterns =[
    # 处理一级回复，不传入parent_comment_id则默认值为None
    url(r'^post-comment/(?P<article_id>\d+)', views.post_comment, name='post_comment'),
    # 处理二级回复
    url(r'^post-comment/(?P<article_id>\d+)/(?P<parent_comment_id>\d+)', views.post_comment, name='comment_reply')
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    url(r'^article/', include('article.urls', namespace='article', app_name='article')),
    url(r'^comment/', include('comment.urls', namespace='comment', app_name='comment')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from django.contrib.auth.models import User
# Create your models here.
from article.models import ArticlePost
from ckeditor.fields import RichTextField


class Comment(MPTTModel):
    article = models.ForeignKey(
        ArticlePost,
        on_delete=models.CASCADE,
        related_name='comment'
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comment'
    )
    body = RichTextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body[:20]

    # 新增mptt树形结构
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children'
    )

    # 二级评论恢复给谁
    reply_to = models.ForeignKey(
        User,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='replyers'
    )

    class MPTTMeta:
        order_insertion_by = ['created']

comment/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model= Comment
        fields = ['body']

comment/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect, reverse

from article.models import ArticlePost
from comment.forms import CommentForm
from .models import Comment
from utils.decorators import login_wrapper

# Create your views here.

# @login_wrapper
def post_comment(request, article_id, parent_comment_id=None):
    article = get_object_or_404(ArticlePost, id=article_id)
    slug = article.slug
    print(article_id, parent_comment_id)
    # 处理post请求
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.article = article
            new_comment.user = request.user

            # 二级回复
            if parent_comment_id:
                print('已请求')
                parent_comment = Comment.objects.get(id=parent_comment_id)
                # 若回复层级超过两级，则转为二级
                new_comment.parent_id = parent_comment.get_root().id
                # 被回复人
                new_comment.reply_to = parent_comment.user
                new_comment.save()
                print('评论已写入')
                return HttpResponse('200 OK')

            new_comment.save()
            # 评论完成刷新该页面,后面优化为aja提交数据，局部刷新
            # return redirect('article:list_article_titles')
            # reverse反转url时需要传参数，要用到kwargs参数，会传入一个字典类型的参数
            # article_detail_url = reverse('article:article_detail', kwargs={'id': article_id, 'slug': slug})
            article_detail_url = '/article/article-detail/%s/%s' % (article_id, slug)
            return redirect(article_detail_url)
        else:
            return HttpResponse("表单有误，重新填写")

    elif request.method == 'GET':
        print('获取评论')
        comment_form = CommentForm()
        context = {
            'comment_form': comment_form,
            'article_id': article_id,
            'parent_comment_id': parent_comment_id
        }
        return render(request, 'comment/reply.html', context)

    else:
        return HttpResponse("仅接受get或者post请求")

templates/comment/reply.html
<!-- 载入静态文件 -->
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>


<body>
    <form
    action="."
    method="POST"
    id="reply_form"
    >
        {% csrf_token %}
        <div class="form-group">
            <div id="test">
                {{ comment_form.media }}
                {{ comment_form.body }}
            </div>
        </div>
    </form>
    <!-- 提交按钮 -->
    <input type="hidden" id="id" name="id" value="">
    <button onclick="confirm_submit({{ article_id }}, {{ parent_comment_id }})" class="btn btn-primary">发送二级回复</button>

    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'popper/popper-1.14.4.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- csrf token -->
    <script src="{% static 'csrf.js' %}"></script>

    <script type="text/javascript">
    $(function(){
        $(".django-ckeditor-widget").removeAttr('style');
    });

    function confirm_submit(article_id, comment_id){
        // 从 ckeditor 中取值
        let content = CKEDITOR.instances['id_body'].getData();
        // 调用 ajax 与后端交换数据
        $.ajax({
            url: '/comment/post-comment/' + article_id + '/' + comment_id,
            {#url:'{% url 'comment:comment_reply' article_id parent_comment_id %}',#}
            type: 'POST',
            data: {body: content},
            // 成功回调
            success: function(e){
                if(e === '200 OK'){
                    parent.location.reload();
                }
            }
        })
    }
    </script>

</body>

</html>