account/urls.py
from django.conf.urls import url
from .import views
from django.contrib.auth import views as auth_views

urlpatterns=[

    #系统自带的登录方法
    # url(r'^login/$', auth_views.login, {'template_name': 'account/login.html'}, name='user_login'),
    #使用自己定义的登录方法
    url(r'^login2/$', views.user_login, name='user_login'),
    # url(r'^logout/$', auth_views.logout, {'template_name': 'account/logout.html'}, name='user_logout'),
    url(r'^logout/$', auth_views.logout, name='user_logout'),
    url(r'^register/$',views.register, name='user_register'),
    url(r'my-infomation/$', views.myself, name='my_infomation'),
]

article/urls.py
from django.conf.urls import url
from . import views, list_views
from haystack.views import SearchView


urlpatterns=[
    url(r'^article-column/$', views.article_column, name='article_column'),
    url(r'^rename-column/$', views.rename_article_column, name='rename_article_column'),
    url(r'^delete-column/$', views.delete_article_column, name='delete_column'),
    url(r'^post-article/$', views.article_post, name='article_post'),
    url(r'^article-list/$', views.article_list, name='article_list'),
    url(r'^delete-article/$', views.delete_article, name='delete_article'),
    url(r'^article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name='article_detail'),
    url(r'^re-edit-article/(?P<article_id>\d+)$', views.re_edit_article, name='re_edit_article'),
    url(r'^list-article-titles/$', list_views.article_titles, name='list_article_titles'),
    url(r'^list-article-titles-bysomeone/(?P<author>[-\w]+)/$', list_views.article_titles_by_someone, name='list_article_titles_bysomeone'),

    url(r'^upload/$', views.upload_img, name='upload_img'),
    # url(r'^search/$', views.MySeachView, name='haystack_search'),
    # SearchView()视图函数，默认使用的HTML模板路径为templates/search/search.html
    url(r'search/$', SearchView(), name='haystack_search'),
]

blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.blog_title, name='blog_title'),
    # 文章详情页，?P<article_id>\d匹配一个数字字符并将该字符赋值给参数article_id,传递给视图函数views.blog_content
    url(r'(?P<article_id>\d)/$', views.blog_content, name='blog_content'),
    url(r'^about/$', views.blog_about, name='blog_about'),
    url(r'^course/$', views.blog_course, name='blog_course'),
    url(r'^contact/$', views.blog_contact, name='blog_contact'),
]

comment/urls.py
from django.conf.urls import url
from . import views

urlpatterns =[
    # 处理一级回复，不传入parent_comment_id则默认值为None
    url(r'^post-comment/(?P<article_id>\d+)', views.post_comment, name='post_comment'),
    # 处理二级回复
    url(r'^post-comment/(?P<article_id>\d+)/(?P<parent_comment_id>\d+)', views.post_comment, name='comment_reply')
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    url(r'^article/', include('article.urls', namespace='article', app_name='article')),
    url(r'^comment/', include('comment.urls', namespace='comment', app_name='comment')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from django.contrib.auth.models import User
from slugify import slugify
from django.utils import timezone
from django.core.urlresolvers import reverse
from PIL import Image
# Create your models here.


class ArticleColumn(models.Model):
    # 用户与栏目是“一对多”关系，所以用ForeignKey,一个用户可以设置多个栏目,此处的user字段对应实际表中的user_id,来自于User表中主键
    user = models.ForeignKey(User, related_name='article_column')
    column = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)

    # 必须要写此方法，要不外键关系返回ArticleColumn object，而不是具体的column值
    def __str__(self):
        return self.column

    class Meta:
        ordering = ('-created',)


class ArticlePost(models.Model):

    author = models.ForeignKey(User, related_name='article')
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn, related_name='article_column')
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now())
    updated = models.DateTimeField(auto_now_add=True)
    # media/%Y%m%d/为图片的真实放置路径，因为settings中已经配置了MEDIA_ROOT为media文件夹，blank=True允许表单的该字段对应值为空，意思是非必填字段
    avatar = models.ImageField(upload_to='%Y%m%d/', blank=True)

    class Meta:
        # ordering = ('title',)
        #对这俩字段建立索引，后面会根据文章id和slug获取文章对象，也能提高读取文章对象速度
        index_together = (('id', 'slug'),)
        ordering = ('-updated',)

    def __str__(self):
        # 实例化该类时会返回对象的title
        return self.title


    def save(self, *args, **kwargs):
        '''
        每个数据模型都有一个save方法，这里重写该方法，目的是要实现self.slug = slugify(self.title)
        :param args:
        :param kwargs:
        :return:
        '''
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id, self.slug])


# class ArticleTags(models.Model):
#     '''
#     文章标签
#     '''
#     tag_name = models.CharField(max_length=20)


class Comments(models.Model):
    user = models.ForeignKey(User, related_name='comment_user')
    article = models.ForeignKey(ArticlePost, related_name='comments')
    body = models.TextField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

article/forms.py
from .models import ArticleColumn, ArticlePost, Comments
from django import forms


class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ('column',)


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        # fields = ('title', 'body')
        fields = ('title', 'body', 'avatar')


class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('body',)

article/views.py
from django.shortcuts import render,HttpResponse, get_object_or_404

from comment.models import Comment
from .models import ArticleColumn, ArticlePost, Comments
from utils.decorators import login_wrapper
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from .forms import ArticleColumnForm, ArticlePostForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import redis
from django.conf import settings
from django.contrib.auth.models import User
from PIL import Image
from .forms import CommentsForm
import json
# Create your views here.


@csrf_exempt
@login_wrapper
def article_column(request):
    '''
    GET请求展示栏目，POST请求增加栏目
    :param request:
    :return:
    '''
    if request.method == 'GET':
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request, "article/column/article_column.html",
                      {'columns': columns, 'column_form': column_form})

    if request.method == 'POST':
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(column=column_name, user_id=request.user.id)
        if columns:
            # 如果数据库中存在
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(column=column_name, user_id=request.user.id)
            return HttpResponse('1')


@csrf_exempt
@login_wrapper
@require_POST
def rename_article_column(request):
    '''
    编辑栏目名称（csrf_exempt装饰器必须放在最上面，否则会403）
    :param request:
    :return:
    '''
    # 获取从前台ajax方式传递的data数据
    column_name = request.POST['column_name']
    column_id = request.POST['column_id']
    try:
        # 根据id查到该条数据
        line = ArticleColumn.objects.get(id=column_id)
        # 将该数据的column字段重新赋值为column_name，即前台的new_column
        line.column = column_name
        # 一定要保存
        line.save()
        return HttpResponse('1')

    except:
        return HttpResponse('0')


@csrf_exempt
@login_wrapper
@require_POST
def delete_article_column(request):
    '''
    删除栏目
    :param request:
    :return:
    '''
    column_id = request.POST['column_id']
    line = ArticleColumn.objects.filter(id=column_id)
    line.delete()
    return HttpResponse('1')


@csrf_exempt
@login_wrapper
def article_post(request):
    '''
    文章发布功能
    :param request:
    :return:
    '''
    if request.method == 'POST':
        # print('已进入article_post视图')
        print('request.FILES的值为：%s' % request.FILES)
        print('request.POST的值为：%s' % request.POST)
        # 实例化表单对象，来自于前端ajax请求
        article_post_form = ArticlePostForm(request.POST, request.FILES)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                # ModelForm 类或者它的子类都具有save()方法，当然实例化后的article_post_form也有此方法，
                # 它的效果是生成该数据对象，并将表单数据保存到数据库
                # commit=False则表示只生成文章数据对象，不保存
                new_article = article_post_form.save(commit=False)
                # 给该文章数据对象设置作者和栏目后再进行保存
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                print('正在更新文章到数据库')
                new_article.avatar = request.FILES.get('avatarrrrr')
                # print('request.POST的值为：%s' % request.POST)
                # print('request.FILES的值为：%s' % request.FILES)
                print('request.FILES的值为：%s' % request.FILES.get('avatarrrrr'))

                print('即将保存')
                new_article.save()
                print('已经保存啦')
                return HttpResponse('1')
            except:
                return HttpResponse('2')
        else:
            return HttpResponse('不合法啊')
    else:
        article_post_form = ArticlePostForm()
        # 获取request.user用户的所有栏目article_column为ArticleColumn模型类中的user字段的related_name,其实等价于
        # article_columns = ArticleColumn.objects.filter(user=request.user)
        # 通过user实例，找到其名下所有的ArticleColumn实例
        article_columns = request.user.article_column.all()
        return render(request, 'article/column/article_post.html', {'article_post_form': article_post_form,
                                                                    'article_columns': article_columns})

from django.core.files.uploadedfile import UploadedFile
@csrf_exempt
def upload_img(request):
    if request.method == 'POST':
        print(3333333333333)
        print(request.FILES)
        print('request.FILES的值为：%s' % request.FILES.get('avatarrrrr'))
        # file = request.FILES.values()
        # wrapped_file = UploadedFile(file)
        # upload = ArticlePost.objects.create(avatar=wrapped_file)
        # upload.save()
        return HttpResponse('OK')


@csrf_exempt
@login_wrapper
def article_list(request):
    '''文章列表'''
    articles = ArticlePost.objects.filter(author=request.user)
    # 将articles对象每3条一页
    pageinator = Paginator(articles, 5)
    # 获取前端传来的page参数
    page = request.GET.get('page')
    try:
        # page()为Paginator对象的一个方法，可以获取指定页面内容，参数必须>=1的整数
        current_page = pageinator.page(page)
        # object_list是Page对象的属性，可以返回该页所有对象列表
        articles = current_page.object_list
    except PageNotAnInteger:
        # 当page参数不是整数时，展示第一页
        current_page = pageinator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        # 当page参数值为空或者没有page参数
        current_page = pageinator.page(pageinator.num_pages)
        articles = current_page.object_list
    return render(request, 'article/column/article_list.html', {'articles': articles, 'page': current_page})


@csrf_exempt
@login_wrapper
def delete_article(request):
    '''
    删除文章
    :param request:
    :return:
    '''
    article_id = request.POST['article_id']
    try:
        line = ArticlePost.objects.get(id=article_id)
        line.delete()
        return HttpResponse('1')
    except:
        return HttpResponse('2')


# @login_wrapper
def article_detail(request, id, slug):
    # print(slug,id)
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    # 连接redis
    r = redis.StrictRedis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB)
    # 总的访问次数，访问一次就+1，一般命名规则为"对象类型：对象ID：对象属性"
    total_views = r.incr('article:{}:views'.format(article.id))
    # zincrby(name, amount, value)方法:根据amount设定的步长增加有序集合name中的value的分值（类似于权重）
    # 实现了每访问一次文章就会将article_ranking中的article.id分值增加1
    # article_ranking中存放的是文章的id用来代表文章，每访问一次该文章就会增加文章的分值
    r.zincrby('article_ranking', 1, article.id)
    # 获取分值排名前十的对象
    article_ranking = r.zrange('article_ranking', 0, -1, desc=True)[:10]
    # 获取排名前十文章的id列表,使用的是列表推导式，先进行for循环，再将每次的的值带入int()方法运算，将结果放在新的列表中
    article_ranking_ids = [int(id) for id in article_ranking]
    print('文章浏览量对应的id：%s' % article_ranking_ids)
    # 查询出排名在前十的文章对象,并放在list中。注意id__in用法：id在article_ranking_ids列表中
    most_viewed = list(ArticlePost.objects.filter(id__in=article_ranking_ids))
    print('文章未排序：%s' % most_viewed)
    # 将获得的列表按照下表索引进行排序，lamda为匿名函数，先运算后面表达式，冒号前的x相当于参数，代表most_viewed列表中文章对象
    # 按照文章的id得到对应的下标,再按照下标进行排序
    most_viewed.sort(key=lambda x: article_ranking_ids.index(x.id))
    print('文章已经排序：%s' % most_viewed)

    # 该作者的所有栏目
    article = ArticlePost.objects.get(id=id)
    print('作者为：%s' % article.author)
    user = User.objects.get(username=article.author)
    print(user.id)
    # 以下两种都行
    # columns = ArticleColumn.objects.filter(user=user)
    columns = ArticleColumn.objects.filter(user=user.id)
    print(columns)
    column_count_dict = {}
    for column in columns:
        column_count = ArticlePost.objects.filter(column=column).count()
        # print(column_count)
        column_count_dict[column]=column_count
        print('%s 栏目的总数是：%s' % (column, column_count))
    print(column_count_dict)

    # 评论功能代码
    if request.method == 'POST':
        comment_form = CommentsForm(data=request.POST)

        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.body = request.POST['body']
            new_comment.article = ArticlePost.objects.get(id=id)
            new_comment.user = request.user
            new_comment.save()
            # return HttpResponse('1')
            comments = Comments.objects.filter(article_id=id)
            print(6666666666666666666)
            print(comments.__len__())

            # for comment in comments:
            #     print(comment.body)
            #     print(comment.created)
            #     global htmls
            #     html = '<a href="#"></a><div style="margin-left: 40px">'+comment.body+'</div><p>还没有评论</p>'
            #     htmls = html+html
            #     print(html)
            #     print('返回了HTML')
            # print(html)
            return render(request, 'article/comment.html',{'article': article, 'comments': comments, 'result': 1})
        else:
            # print('返回是2')
            return HttpResponse('2')
    else:
        comment_form = CommentsForm()

    comments = Comment.objects.filter(article=id)
    return render(request, 'article/column/article_detail2.html', {'article': article,
                                                                  'total_views': total_views,
                                                                  'most_viewed': most_viewed,
                                                                  'columns': columns,
                                                                  'column_count_dict': column_count_dict,
                                                                  'comment_form': comment_form,
                                                                  'result': 1,
                                                                   'comments':comments
                                                                  })


@csrf_exempt
# @login_wrapper
def re_edit_article(request, article_id):
    '''
    再次编辑文章
    :param request:
    :return:
    '''

templates/article/column/article_column.html
{% extends 'article/base.html' %}
{% load staticfiles %}
{% block title %}article column{% endblock %}
{% block content %}
<div>
    <p class="text-right"><button id="add_column" onclick="add_column()" class="btn btn-primary">add column</button></p>
    <table class="table table-hover table-bordered">
        <tr>
            <td>序号</td>
            <td>栏目名</td>
            <td>操作</td>
        </tr>

        {% for column in columns %}
        <tr>
{#            第一列，序号，{forloop在for循环中有效，forloop.counter代表当前循环的次数从1开始，可以做序号#}
            <td>{{ forloop.counter }}</td>
{#            <td>{{ forloop.counter0 }}</td>#}
            <td>{{ column.column }}</td>
            <td>
                <a name="edit" href="javascript:" onclick="edit_column(this,{{ column.id }})">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                <a name="delete" href="javascript:" onclick="delete_column(this,{{ column.id }})">
                    <span class="glyphicon glyphicon-trash" style="margin-left: 20px"></span>
                </a>
            </td>
        </tr>
        {% empty %}
        <p>还没有栏目，太懒了</p>
        {% endfor %}
    </table>

{% include 'paginator.html' %}

</div>
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
    <script type="text/javascript">
            function add_column(){
                {#增加栏目函数#}
                var index = layer.open({
                    type:1,
                    {#skin:"layui-layer-rim",#}
                    area:['400px','200px'],
                    title:'新增栏目',
                    content:'<div class="text-center" style="margin-top:20px"><p>请输入栏目名称</p><p>{{ column_form.column }}</p></div>',
                    btn:['确定','取消'],
                    yes:function(index, layero) {
                        {#此处id_column为forms表单渲染出的输入框元素id#}
                        column_name = $('#id_column').val();
                        $.ajax({
                            url:'{% url 'article:article_column' %}',
                            type: 'POST',
                            data:{'column': column_name},
                            success:function (e) {
                                if (e == '1') {
                                    parent.location.reload();
                                    layer.msg('goOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOooooooood')
                                } else {
                                    layer.msg("此栏目已存在");
                                }
                            }
                        });
                    },
                    {#btn2为取消按钮#}
                    btn2:function(index, layero){
                        layer.close(index);
                    }
                });
            }
            
            function edit_column(the, column_id){
                {# 取出原始的栏目名称，当前元素.父层级tr.子层级td.第二个td元素.的值 #}
                var name = $(the).parents("tr").children("td").eq(1).text();
                var index = layer.open({
                    type:1,
                    area: ['400px','200px'],
                    title: '编辑栏目',
                    content: '<div class="text-center style="margin-top:20px">' +
                                '<p>请编辑栏目名称</p>'+
                                '<p><input type="text" id="new_name" value="'+name+'"></p>'+
                            '</div>',
                    btn: ['确定','取消'],
                    yes:function (index, layero) {
                         {#获取input输入框的新栏目值#}
                        new_name = $('#new_name').val();
                        $.ajax({
                            url:"{% url 'article:rename_article_column' %}",
                            type:"POST",
                            data: {'column_id': column_id, 'column_name': new_name},
                             {#后台处理成功时回调函数，e为后台返回的值#}
                            success:function (e) {
                                if (e=='1'){
                                    {#修改成功后刷新页面#}
                                    parent.location.reload();
                                    layer.msg("good");
                                } else{
                                    layer.msg("修改失败");
                                }
                            },
                        });

                    },
                });
            }
            
            function delete_column(the,column_id) {
                column_name = $(the).parents("tr").children("td").eq(1).text();
                var index = layer.open({
                    type:1,
                    area:['400px', '200px'],
                    title:'删除栏目',
                    {# 注意此处的变量引用方式'+column_name+' #}
                    content:'<div class="text-center style="margin-top:80px">' +
                                '<p>确定要删除【'+column_name+'】栏目吗？</p>'+
                            '</div>',
                    btn:['确定','取消'],
                    yes:function (index, layero) {
                        $.ajax({
                            url:"{% url 'article:delete_column' %}",
                            type:'POST',
                            data:{'column_id': column_id},
                            success:function (e) {
                                if (e=='1'){
                                    parent.location.reload()
                                    layer.msg("已删除")
                                } else{
                                    layer.msg("删除失败")
                                }
                            },
                        });
                    },
                });
            }
    </script>

{% endblock %}

templates/article/column/article_detail2.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}article detail{% endblock %}

{% block content %}
<div class="container">
    <div class="col-md-9">
        <header>
            <h1>{{ article.title }}</h1>
                <p class="text-muted">
                    {# 将作者信息追加到url中，并再url中捕获该参数，再到视图中提取该参数的值，查询出该作者对应的文章#}
                    <a href="{% url 'article:list_article_titles_bysomeone' article.author %}">{{ article.author }}</a>
                    {{ total_views }}次阅读
                    <a href="{% url 'article:re_edit_article' article.id %}">编辑</a>
{#                    <p>本文共{{ article.body|wordcount }}个字,阅读需分钟</p>#}
                </p>
        </header>

        <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}">

        <div id="editormd-view">
            <textarea id="append-test" style="display: none">
    {{ article.body }}
            </textarea>
        </div>



<!-- 改动 显示评论 部分 -->
<!-- 不要漏了 load mptt_tags！ -->
{% load mptt_tags %}
<h4>共有{{ comments.count }}条评论</h4>
<div class="row">
    <!-- 遍历树形结构 -->
    {% recursetree comments %}
        <!-- 给 node 取个别名 comment -->
        {% with comment=node %}
            <div class="{% if comment.reply_to %}
                        offset-1 col-11
                        {% else %}
                        col-12
                        {% endif %}"
            >
                <hr>
                <p>
                    <strong style="color: pink">
                        {{ comment.user }}
                    </strong>

                    {% if comment.reply_to %}
                        <i class="far fa-arrow-alt-circle-right"
                           style="color: cornflowerblue;"
                        ></i>
                        <strong style="color: pink">
                            {{ comment.reply_to }}
                        </strong>
                    {% endif %}

                </p>
                <div>{{ comment.body|safe }}</div>

                <div>
                    <span style="color: gray">
                        {{ comment.created|date:"Y-m-d H:i" }}
                    </span>

                    <!-- modal 按钮 -->
                    <button type="button"
                            class="btn btn-light btn-sm text-muted"
                            onclick="load_modal({{ article.id }}, {{ comment.id }})"
                    >
                        回复
                    </button>
                </div>

                <!-- Modal -->
                <div class="modal fade"
                     id="comment_{{ comment.id }}"
                     tabindex="-1"
                     role="dialog"
                     aria-labelledby="CommentModalCenter"
                     aria-hidden="true"
                >
                    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                        <div class="modal-content" style="height: 480px">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalCenterTitle">回复 {{ comment.user }}：</h5>
                            </div>
                            <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                        </div>

                    </div>
                </div>

                {% if not comment.is_leaf_node %}
                    <div class="children">
                        {{ children }}
                    </div>
                {% endif %}
            </div>


        {% endwith %}
    {% endrecursetree %}
</div>



    <!-- 评论区域 -->
<div class="col-12">

    </div>

    <!-- 发表评论 -->
    <br>
    {% if user.is_authenticated %}
        <div>
            <form
                action="{% url 'comment:post_comment' article.id %}"
                method="POST"
            >
            {% csrf_token %}
                <div class="form-group">
                    <label for="body">
                        <strong>
                            我也要发言：
                        </strong>
                    </label>
                    <textarea
                        type="text"
                        class="form-control"
                        id="body"
                        name="body"
                        rows="2"></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary ">发送</button>
            </form>
        </div>
        <br>
    {% else %}
        <br>
        <h5 class="row justify-content-center">
            请<a href="{% url 'account:user_login' %}?cur_url={{ request.path }}">登录</a>后回复
        </h5>
        <br>
    {% endif %}



{#    勿动#}

    </div>
    <div class="col-md-3">
        <p class="text-center">最受欢迎文章</p>
        <ol>
            {% for article_rank in most_viewed %}
            <li>
                    <a href="{{ article_rank.get_absolute_url }}">{{ article_rank.title|slice:'25' }}</a>
            </li>
            {% endfor %}
        </ol>

        <p class="text-center">{{ article.author }}的栏目</p>
        <ol>
            {% for column,count in column_count_dict.items %}
            <li>
                <a href="{% url 'article:list_article_titles_bysomeone' article.author %}?column={{ column }}">{{ column }}({{ count }})</a>
            </li>
            {% endfor %}
        </ol>
    </div>

</div>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'editor/lib/marked.min.js' %}"></script>
    <script src="{% static 'editor/lib/prettify.min.js' %}"></script>
    <script src="{% static 'editor/lib/raphael.min.js' %}"></script>
    <script src="{% static 'editor/lib/underscore.min.js' %}"></script>
    <script src="{% static 'editor/lib/sequence-diagram.min.js' %}"></script>
    <script src="{% static 'editor/lib/flowchart.min.js' %}"></script>
    <script src="{% static 'editor/lib/jquery.flowchart.min.js' %}"></script>
    <script src="{% static 'editor/editormd.js' %}"></script>




    <script src="{% static 'popper/popper-1.14.4.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- csrf token -->
    <script src="{% static 'csrf.js' %}"></script>


    <script type="text/javascript" src="{% static 'js/layer.js'%}"></script>

    <script type="text/javascript">
            $(function () {
                editormd.markdownToHTML("editormd-view",{
                    htmlDecode:"style,script,iframe",
                    emoji:true,
                    tasklist:true,
                    flowChart:true,
                    tex:true,
                    sequenceDiagram:true,
                });
            });
    </script>

    <script type="text/javascript">
            function commit_comment() {
                var formData = new FormData();
                formData.append('body',$('#id_body').val());
                $.ajax({
                    url:"{% url 'article:article_detail' article.id article.slug%}",
                    type:'POST',
                    {#告诉jQuery不要去处理发送的数据, 发送对象。#}
                    processData : false,
                    {#告诉jQuery不要去设置Content-Type请求头#}
                    contentType : false,
                    async : false,
                    data:formData,
                    {#dataType: "json",#}
{#                    此处返回的datas是HTML格式#}
                    success:function (datas) {
                      if(1){
                          $('#comments').html(datas);
                          layer.msg("成功发布");
                          resettext();
                      }else if(datas=='2'){
                          layer.msg("请填写内容");
                      } else{
                          layer.msg("项目名和内容必须填写");
                      }
                      },
              });
          }
    </script>

    <script type="text/javascript">
        function resettext(){
            $('#id_body').val('');
        }
    </script>


    <!-- 新增代码，唤醒二级回复的 modal -->
<script type="text/javascript">

    // 加载 modal
    function load_modal(article_id, comment_id) {
        let modal_body = '#modal_body_' + comment_id;
        let modal_id = '#comment_' + comment_id;

        // 加载编辑器
        if ($(modal_body).children().length === 0) {
            let content = '<iframe src="/comment/post-comment/' +
                article_id +
                '/' +
                comment_id +
                '"' +
                ' frameborder="0" style="width: 100%; height: 100%;" id="iframe_' +
                comment_id +
                '"></iframe>';
            $(modal_body).append(content);
        };
        $(modal_id).modal('show');
    }
</script>


{#    获取当前的url,登录后跳转至该页面#}
<script type="text/javascript">
        function cur_href() {
            var cur_url = window.location.href;
            $.ajax({
                url: '{% url 'account:user_login' %}',
                type: 'GET',
                data: {cur_url:cur_url},
            })
        }
</script>

<script type="text/javascript">
        function login() {
            {#var cur_url = window.location.href;#}
            window.location.href = '{% url 'account:user_login' %}';

            $.ajax({
                    url: '{% url 'account:user_login' %}',
                    type: 'GET',
                    {#data: {cur_url:cur_url},#}
                    success:function (data) {
                        if (data=='ok') {
                            window.location.href = '{% url 'article:list_article_titles' %}';
                        }
                    }
                })
        }
</script>



{% endblock %}