blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.blog_title, name='blog_title'),
    # 文章详情页，?P<article_id>\d匹配一个数字字符并将该字符赋值给参数article_id,传递给视图函数views.blog_content
    url(r'(?P<article_id>\d)/$', views.blog_content, name='blog_content'),
    url(r'^about/$', views.blog_about, name='blog_about'),
    url(r'^course/$', views.blog_course, name='blog_course'),
    url(r'^contact/$', views.blog_contact, name='blog_contact'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    url(r'^article/', include('article.urls', namespace='article', app_name='article')),
    url(r'^comment/', include('comment.urls', namespace='comment', app_name='comment')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.


class BlogArticles(models.Model):

    title = models.CharField(max_length=300)
    author = models.ForeignKey(User, related_name="blog_posts")
    body = models.TextField()
    #故意写成now(),看看是否报错----会报错
    publish = models.DateTimeField(default=timezone.now)

    class Meta:
        # BlogArticles实例对象在后台展示时，按照publish字段倒序排列
        ordering = ("-publish",)


    # 先不写这里
    # def __str__(self):
    #     return self.title


class Contact(models.Model):

    name = models.CharField(max_length=20)
    content = models.TextField()
    email = models.EmailField(null=True)

blog/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    # type = forms.ChoiceField()
    # name = forms.CharField(max_length=20)
    # content = forms.Textarea()
    # email = forms.EmailField(required=False)

    class Meta:
        model = Contact
        fields = ( 'name', 'content', 'email')

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogArticles
from django.http import HttpResponse
from utils.decorators import login_wrapper
from .forms import ContactForm
# Create your views here.


def blog_title(request):
    blogs = BlogArticles.objects.all()
    return render(request, "blog/title.html", {'blogs': blogs})


def blog_content(request, article_id):
    # article = BlogArticles.objects.get(id=article_id)
    # 没有找到对象显示404页面
    article = get_object_or_404(BlogArticles, id= article_id)
    return render(request, "blog/content.html", {'article': article})


@login_wrapper
def blog_about(request):

    return HttpResponse("关于本站，只有登录才能看哦")


@login_wrapper
def blog_course(request):

    return HttpResponse('恭喜你，进入到了秘密花园')


@login_wrapper
def blog_contact(request):
    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact = contact_form.save(commit=False)
            contact.type = request.POST.get('type')
            contact.name = request.POST['name']
            contact.content = request.POST['content']
            contact.email = request.POST['email']
            contact.save()
            return HttpResponse('1')
    else:
        contact_form = ContactForm()
    return render(request, 'blog/contact.html', {'contact_form': contact_form})

templates/blog/contact.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="." method="post">{% csrf_token %}
        <table>
        {{ contact_form.as_table }}
        </table>
        <input type="button" value="提交" onclick="commit_feedback()">
    </form>
</body>

<script type="text/javascript" src='{% static "js/jquery.js"%}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>

<script type="text/javascript">

    function commit_feedback() {
        var formData= new FormData();
        formData.append('name',$('#id_name').val());
        formData.append('content',$('#id_content').val());
        formData.append('email',$('#id_email').val());

        $.ajax({
            url:'{% url 'blog:blog_contact' %}',
            type:'POST',
            data: formData,
            {#告诉jQuery不要去处理发送的数据, 发送对象。#}
            processData : false,
            {#告诉jQuery不要去设置Content-Type请求头#}
            contentType : false,
            success:function(e){
                if (e=='1'){
                    layer.msg("提交成功");
                    location.href = "{% url 'blog:blog_title' %}";
                }
            },
        });
    }
</script>

</html>

templates/blog/content.html
{% extends "base.html" %}

{% block title %}blog titles{% endblock %}

{% block content %}
    <div class="row text-center vertical-middle-sm">
        <h1>{{ article.title }}</h1>
    </div>

    <div class="row">
        <div class="col-xs-12 col-md-8">
            <p class="text-center"><span>{{ article.author }}</span><span style="margin-left: 20px">{{ article.publish }}</span></p>
             <div>
                {{ article.body }}
            </div>
        </div>

        <div class="col-xs-6 col-md-4">
            <h2 >广告</h2>
            <p >广告位招租</p>
            <a href="https://dm30webimages.lynkco.com.cn/LynkCoPortal/Content/images/chenxing2/03yushou/pc/4.jpg">
                <img width="200px" src="https://dm30webimages.lynkco.com.cn/LynkCoPortal/Content/images/chenxing2/03yushou/pc/4.jpg">
            </a>
        </div>
    </div>
{% endblock %}

templates/blog/title.html
{% extends "base.html" %}

{% block title %}blog articles{% endblock %}

{% block content %}
    <div class="row text-center vertical-middle-sm">
        <h1>我的博客</h1>
    </div>
    <div class="row">
        <div class="col-xs-12 col-md-8">
            <ul>
            {% for blog in blogs %}
                <a href={{ blog.id }}><li>{{ blog.title }}</li></a>
            {% endfor %}
            </ul>
        </div>
        <div class="col-xs-6 col-md-4">
            <h2 >广告位</h2>
            <p >广告招租</p>
            <img width="200px" src="https://dm30webimages.lynkco.com.cn/LynkCoPortal/Content/images/chenxing2/03yushou/pc/4.jpg">
        </div>
    </div>
{% endblock %}