account/urls.py
from django.conf.urls import url
from .import views
from django.contrib.auth import views as auth_views

urlpatterns=[

    #系统自带的登录方法
    # url(r'^login/$', auth_views.login, {'template_name': 'account/login.html'}, name='user_login'),
    #使用自己定义的登录方法
    url(r'^login2/$', views.user_login, name='user_login'),
    # url(r'^logout/$', auth_views.logout, {'template_name': 'account/logout.html'}, name='user_logout'),
    url(r'^logout/$', auth_views.logout, name='user_logout'),
    url(r'^register/$',views.register, name='user_register'),
    url(r'my-infomation/$', views.myself, name='my_infomation'),
]

article/urls.py
from django.conf.urls import url
from . import views, list_views
from haystack.views import SearchView


urlpatterns=[
    url(r'^article-column/$', views.article_column, name='article_column'),
    url(r'^rename-column/$', views.rename_article_column, name='rename_article_column'),
    url(r'^delete-column/$', views.delete_article_column, name='delete_column'),
    url(r'^post-article/$', views.article_post, name='article_post'),
    url(r'^article-list/$', views.article_list, name='article_list'),
    url(r'^delete-article/$', views.delete_article, name='delete_article'),
    url(r'^article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name='article_detail'),
    url(r'^re-edit-article/(?P<article_id>\d+)$', views.re_edit_article, name='re_edit_article'),
    url(r'^list-article-titles/$', list_views.article_titles, name='list_article_titles'),
    url(r'^list-article-titles-bysomeone/(?P<author>[-\w]+)/$', list_views.article_titles_by_someone, name='list_article_titles_bysomeone'),

    url(r'^upload/$', views.upload_img, name='upload_img'),
    # url(r'^search/$', views.MySeachView, name='haystack_search'),
    # SearchView()视图函数，默认使用的HTML模板路径为templates/search/search.html
    url(r'search/$', SearchView(), name='haystack_search'),
]

blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.blog_title, name='blog_title'),
    # 文章详情页，?P<article_id>\d匹配一个数字字符并将该字符赋值给参数article_id,传递给视图函数views.blog_content
    url(r'(?P<article_id>\d)/$', views.blog_content, name='blog_content'),
    url(r'^about/$', views.blog_about, name='blog_about'),
    url(r'^course/$', views.blog_course, name='blog_course'),
    url(r'^contact/$', views.blog_contact, name='blog_contact'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    url(r'^article/', include('article.urls', namespace='article', app_name='article')),
    url(r'^comment/', include('comment.urls', namespace='comment', app_name='comment')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
    <head>
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
    	<title>{% block title %}{% endblock %}</title>
    	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    </head>
    <body>
        {% include "header.html" %}
        <div class="container">
        	{% block content %}{% endblock %}
        </div>
        {% include "footer.html" %}
        {% block javascritp %}{% endblock %}
    </body>
</html>

templates/footer.html
<div class="container">
    <p class="text-center">Copyright @ www.gc.com</p>
</div>

templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand"  href="#">
                <img style="margin-bottom:5px" src="{% static '/images/logo.png' %}" width="50px" height="30px">
            </a>
	</div>
	<div>
	    <ul class="nav navbar-nav" role="navigation">
{#		<li><a href="{% url 'home' %}">HOME</a></li>#}
{#            <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>#}
            <li><a href="{% url 'article:list_article_titles' %}">文章</a></li>
            <li><a href="{% url 'article:article_list' %}">文章管理</a></li>

            {% if user.is_authenticated %}
            <li><a href="{% url 'article:list_article_titles_bysomeone' request.user %}">我的文章</a></li>
            {% endif %}

{#            <li><a href="{% url 'blog:blog_course' %}">课程(登录后可查看)</a></li>#}
            <li><a href="{% url 'blog:blog_about' %}">关于本站</a></li>
            <li><a href="{% url 'blog:blog_contact' %}">联系我们</a></li>
        <li>
            <form action="{% url 'article:haystack_search' %}" method="get">
                {#   此处的name='q'为固定写法，不能修改为其他属性值    #}
                <input type="text" id="kw" name="q" placeholder="请输入关键字">
                <input type="submit" id="search" value="搜索">
            </form>
        </li>
	    </ul>

	    <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
{#        如果登录验证通过#}
		{% if user.is_authenticated %}
		    <li class="dropdown">
                    <div class="dropdown" style="margin-top:8px">
                        <button class='btn btn-default dropdown-toggle' type='button' id='dropdownMenu' data-toggle='dropdown'>
                            欢迎您：{{ user.username }}
{#                            ，欢迎{{ request.session.username }}#}
                            <span class='caret'></span>
                        </button>

                        <ul class="dropdown-menu">
                            <li><a href="#">修改密码</a></li>
                            <li><a href="{% url 'account:my_infomation' %}">个人信息</a></li>
                            <li><a href="{% url 'article:article_column' %}">后台管理</a></li>
                        </ul>
                    </div>
            </li>

		    <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
		    {% else %}
		    <li><a href="{% url 'account:user_login' %}">Login</a></li>
            <li><a href="{% url 'account:user_register' %}">Sign up</a></li>
		{% endif %}
	    </ul>
	</div>
    </nav>
</div>
<script src="{% static 'js/jquery.js'%}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

{#搜索框样式#}
<style type="text/css">
    #box{
        width: 380px;
        margin: 30px auto;
        font-family: 'Microsoft YaHei';
        font-size: 14px;
    }
    #kw{
        width: 200px;
        border: 1px solid #e2e2e2;
        height: 30px;
        float: left;
        background-image: url(/static/images/search.jpg);
        background-repeat: no-repeat;
        background-size: 25px;
        background-position:5px center;
        padding:0 0 0 40px;
        {#控制距离上边距#}
        margin-top: 7px;
    }
    #search{
        width: 78px;
        height: 30px;
        float: right;
        background: black;
        color: white;
        text-align: center;
        line-height: 32px;
        cursor: pointer;
        margin-top: 7px;
    }

</style>

templates/paginator.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">上一页</a>
        {% endif %}

        <span class="current">
            Page{{ page.number }} of {{ page.paginator.num_pages }}
        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">下一页</a>
        {% endif %}
    </span>
</div>